import Head from "next/head";
import Image from "next/image";
import { Code } from "@/src/components/Code";
import { Header } from "@/src/components/Header";
import { Title } from "@/src/components/Title";
import { Links } from "@/src/components/Links";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
import CodeStyles from "@/src/components/Code.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Code page="about"
          >
            <code className={CodeStyles.code}>pages/about.js</code>
          </Code>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <Title title="about" />

        <Links />
        
      </main>
    </>
  );
}
